title: 심 규공
logo: "/images/mee.jpg" 
description: Data Analytics/Science 
  <br><br>
  +3년의 상품 개발 및 제휴로 근무, 데이터에 대한 관심과 중요성을 깨닫고 커리어 전환.
  <br>
  +15년 다이어트 관한 도메인 지식으로 데이터 분석.
  <br><br>
  010 2860 1218
  <br>
  kyug.shim@gmail.com
  <br><br>
  <a href="/pdf/resume.pdf">View My Resume</a>
show_downloads: 
google_analytics: UA-145070215-1
theme: jekyll-theme-minimal
